/*
 * system.h - SOPC Builder system and BSP software package information
 *
 * Machine generated for CPU 'cpu_0' in SOPC Builder design 'Nios'
 * SOPC Builder design path: ../../Nios.sopcinfo
 *
 * Generated: Wed Apr 15 16:11:39 CEST 2020
 */

/*
 * DO NOT MODIFY THIS FILE
 *
 * Changing this file will have subtle consequences
 * which will almost certainly lead to a nonfunctioning
 * system. If you do modify this file, be aware that your
 * changes will be overwritten and lost when this file
 * is generated again.
 *
 * DO NOT MODIFY THIS FILE
 */

/*
 * License Agreement
 *
 * Copyright (c) 2008
 * Altera Corporation, San Jose, California, USA.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * This agreement shall be governed in all respects by the laws of the State
 * of California and by the laws of the United States of America.
 */

#ifndef __SYSTEM_H_
#define __SYSTEM_H_

/* Include definitions from linker script generator */
#include "linker.h"


/*
 * CPU configuration
 *
 */

#define ALT_CPU_ARCHITECTURE "altera_nios2_gen2"
#define ALT_CPU_BIG_ENDIAN 0
#define ALT_CPU_BREAK_ADDR 0x05040820
#define ALT_CPU_CPU_ARCH_NIOS2_R1
#define ALT_CPU_CPU_FREQ 100000000u
#define ALT_CPU_CPU_ID_SIZE 1
#define ALT_CPU_CPU_ID_VALUE 0x00000000
#define ALT_CPU_CPU_IMPLEMENTATION "fast"
#define ALT_CPU_DATA_ADDR_WIDTH 0x1b
#define ALT_CPU_DCACHE_LINE_SIZE 0
#define ALT_CPU_DCACHE_LINE_SIZE_LOG2 0
#define ALT_CPU_DCACHE_SIZE 0
#define ALT_CPU_EXCEPTION_ADDR 0x02000020
#define ALT_CPU_FLASH_ACCELERATOR_LINES 0
#define ALT_CPU_FLASH_ACCELERATOR_LINE_SIZE 0
#define ALT_CPU_FLUSHDA_SUPPORTED
#define ALT_CPU_FREQ 100000000
#define ALT_CPU_HARDWARE_DIVIDE_PRESENT 0
#define ALT_CPU_HARDWARE_MULTIPLY_PRESENT 1
#define ALT_CPU_HARDWARE_MULX_PRESENT 0
#define ALT_CPU_HAS_DEBUG_CORE 1
#define ALT_CPU_HAS_DEBUG_STUB
#define ALT_CPU_HAS_EXTRA_EXCEPTION_INFO
#define ALT_CPU_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define ALT_CPU_HAS_ILLEGAL_MEMORY_ACCESS_EXCEPTION
#define ALT_CPU_HAS_JMPI_INSTRUCTION
#define ALT_CPU_ICACHE_LINE_SIZE 32
#define ALT_CPU_ICACHE_LINE_SIZE_LOG2 5
#define ALT_CPU_ICACHE_SIZE 16384
#define ALT_CPU_INST_ADDR_WIDTH 0x1b
#define ALT_CPU_NAME "cpu_0"
#define ALT_CPU_NUM_OF_SHADOW_REG_SETS 0
#define ALT_CPU_OCI_VERSION 1
#define ALT_CPU_RESET_ADDR 0x02000000


/*
 * CPU configuration (with legacy prefix - don't use these anymore)
 *
 */

#define NIOS2_BIG_ENDIAN 0
#define NIOS2_BREAK_ADDR 0x05040820
#define NIOS2_CPU_ARCH_NIOS2_R1
#define NIOS2_CPU_FREQ 100000000u
#define NIOS2_CPU_ID_SIZE 1
#define NIOS2_CPU_ID_VALUE 0x00000000
#define NIOS2_CPU_IMPLEMENTATION "fast"
#define NIOS2_DATA_ADDR_WIDTH 0x1b
#define NIOS2_DCACHE_LINE_SIZE 0
#define NIOS2_DCACHE_LINE_SIZE_LOG2 0
#define NIOS2_DCACHE_SIZE 0
#define NIOS2_EXCEPTION_ADDR 0x02000020
#define NIOS2_FLASH_ACCELERATOR_LINES 0
#define NIOS2_FLASH_ACCELERATOR_LINE_SIZE 0
#define NIOS2_FLUSHDA_SUPPORTED
#define NIOS2_HARDWARE_DIVIDE_PRESENT 0
#define NIOS2_HARDWARE_MULTIPLY_PRESENT 1
#define NIOS2_HARDWARE_MULX_PRESENT 0
#define NIOS2_HAS_DEBUG_CORE 1
#define NIOS2_HAS_DEBUG_STUB
#define NIOS2_HAS_EXTRA_EXCEPTION_INFO
#define NIOS2_HAS_ILLEGAL_INSTRUCTION_EXCEPTION
#define NIOS2_HAS_ILLEGAL_MEMORY_ACCESS_EXCEPTION
#define NIOS2_HAS_JMPI_INSTRUCTION
#define NIOS2_ICACHE_LINE_SIZE 32
#define NIOS2_ICACHE_LINE_SIZE_LOG2 5
#define NIOS2_ICACHE_SIZE 16384
#define NIOS2_INST_ADDR_WIDTH 0x1b
#define NIOS2_NUM_OF_SHADOW_REG_SETS 0
#define NIOS2_OCI_VERSION 1
#define NIOS2_RESET_ADDR 0x02000000


/*
 * Define for each module class mastered by the CPU
 *
 */

#define __ALTERA_AVALON_JTAG_UART
#define __ALTERA_AVALON_NEW_SDRAM_CONTROLLER
#define __ALTERA_AVALON_ONCHIP_MEMORY2
#define __ALTERA_AVALON_SGDMA
#define __ALTERA_AVALON_TIMER
#define __ALTERA_AVALON_UART
#define __ALTERA_ETH_TSE
#define __ALTERA_NIOS2_GEN2
#define __ALTPLL


/*
 * System configuration
 *
 */

#define ALT_DEVICE_FAMILY "Cyclone 10 LP"
#define ALT_ENHANCED_INTERRUPT_API_PRESENT
#define ALT_IRQ_BASE NULL
#define ALT_LOG_PORT "/dev/null"
#define ALT_LOG_PORT_BASE 0x0
#define ALT_LOG_PORT_DEV null
#define ALT_LOG_PORT_TYPE ""
#define ALT_NUM_EXTERNAL_INTERRUPT_CONTROLLERS 0
#define ALT_NUM_INTERNAL_INTERRUPT_CONTROLLERS 1
#define ALT_NUM_INTERRUPT_CONTROLLERS 1
#define ALT_STDERR "/dev/uart_0"
#define ALT_STDERR_BASE 0x5041000
#define ALT_STDERR_DEV uart_0
#define ALT_STDERR_IS_UART
#define ALT_STDERR_PRESENT
#define ALT_STDERR_TYPE "altera_avalon_uart"
#define ALT_STDIN "/dev/uart_0"
#define ALT_STDIN_BASE 0x5041000
#define ALT_STDIN_DEV uart_0
#define ALT_STDIN_IS_UART
#define ALT_STDIN_PRESENT
#define ALT_STDIN_TYPE "altera_avalon_uart"
#define ALT_STDOUT "/dev/uart_0"
#define ALT_STDOUT_BASE 0x5041000
#define ALT_STDOUT_DEV uart_0
#define ALT_STDOUT_IS_UART
#define ALT_STDOUT_PRESENT
#define ALT_STDOUT_TYPE "altera_avalon_uart"
#define ALT_SYSTEM_NAME "Nios"


/*
 * altpll_0 configuration
 *
 */

#define ALTPLL_0_BASE 0x5041040
#define ALTPLL_0_IRQ -1
#define ALTPLL_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define ALTPLL_0_NAME "/dev/altpll_0"
#define ALTPLL_0_SPAN 16
#define ALTPLL_0_TYPE "altpll"
#define ALT_MODULE_CLASS_altpll_0 altpll


/*
 * freertos configuration
 *
 */

#define GOT_TSE_MAC_0 1
#define OS_CHECK_FOR_STACK_OVERFLOW 2
#define OS_IDLE_SHOULD_YIELD 0
#define OS_KERNEL_INTERRUPT_PRIORITY 1
#define OS_MAX_CO_ROUTINE_PRIORITIES 2
#define OS_MAX_PRIORITIES 5
#define OS_MAX_SYSCALL_INTERRUPT_PRIORITY 3
#define OS_MAX_TASK_NAME_LEN 40
#define OS_MINIMAL_STACK_SIZE 4096
#define OS_QUEUE_REGISTRY_SIZE 0
#define OS_THREAD_SAFE_NEWLIB 1
#define OS_TICKS_PER_SEC TIMER_0_TICKS_PER_SEC
#define OS_TICK_RATE_HZ 1000
#define OS_TIMER_QUEUE_LENGTH 10
#define OS_TIMER_TASK_PRIORITY 5
#define OS_TOTAL_HEAP_SIZE 2097152
#define OS_USE_16_BIT_TICKS 0
#define OS_USE_ALTERNATIVE_API 0
#define OS_USE_COUNTING_SEMAPHORES 1
#define OS_USE_CO_ROUTINES 0
#define OS_USE_IDLE_HOOK 0
#define OS_USE_MALLOC_FAILED_HOOK 0
#define OS_USE_MUTEXES 1
#define OS_USE_PREEMPTION 1
#define OS_USE_RECURSIVE_MUTEXES 1
#define OS_USE_TICK_HOOK 0
#define OS_USE_TRACE_FACILITY 1
#define OS_UXTASKGETSTACKHIGHWATERMARK 1
#define OS_UXTASKPRIORITYGET 1
#define OS_VTASKCLEANUPRESOURCES 0
#define OS_VTASKDELAY 1
#define OS_VTASKDELAYUNTIL 1
#define OS_VTASKDELETE 1
#define OS_VTASKPRIORITYSET 1
#define OS_VTASKSUSPEND 1
#define PHY_COUNT 1
#define TSE_MY_SYSTEM 1


/*
 * hal configuration
 *
 */

#define ALT_INCLUDE_INSTRUCTION_RELATED_EXCEPTION_API
#define ALT_MAX_FD 16
#define ALT_SYS_CLK TIMER_0
#define ALT_TIMESTAMP_CLK none


/*
 * jtag_uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_jtag_uart_0 altera_avalon_jtag_uart
#define JTAG_UART_0_BASE 0x5041050
#define JTAG_UART_0_IRQ 2
#define JTAG_UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define JTAG_UART_0_NAME "/dev/jtag_uart_0"
#define JTAG_UART_0_READ_DEPTH 64
#define JTAG_UART_0_READ_THRESHOLD 8
#define JTAG_UART_0_SPAN 8
#define JTAG_UART_0_TYPE "altera_avalon_jtag_uart"
#define JTAG_UART_0_WRITE_DEPTH 64
#define JTAG_UART_0_WRITE_THRESHOLD 8


/*
 * lwip configuration
 *
 */

#define CONF_LWIP_CHECKSUM_CHECK_IP 1
#define CONF_LWIP_CHECKSUM_CHECK_TCP 1
#define CONF_LWIP_CHECKSUM_CHECK_UDP 1
#define CONF_LWIP_CHECKSUM_GEN_IP 1
#define CONF_LWIP_CHECKSUM_GEN_TCP 1
#define CONF_LWIP_CHECKSUM_GEN_UDP 1
#define CONF_LWIP_DEFAULT_TTL 64
#define CONF_LWIP_IP_FORWARD 0
#define CONF_LWIP_LOOPBACK 0
#define CONF_LWIP_LOOPBACKIF 0
#define CONF_LWIP_MEM_SIZE 32768
#define CONF_LWIP_OVERFLOW_CHECK 0
#define CONF_LWIP_PBUF_COUNT 32
#define CONF_LWIP_PROTO_AUTOIP 0
#define CONF_LWIP_PROTO_DHCP 1
#define CONF_LWIP_PROTO_DNS 1
#define CONF_LWIP_PROTO_ICMP 1
#define CONF_LWIP_PROTO_IGMP 1
#define CONF_LWIP_PROTO_SNMP 0
#define CONF_LWIP_PROTO_TCP 1
#define CONF_LWIP_PROTO_UDP 1
#define CONF_LWIP_PROTO_VLAN 0
#define CONF_LWIP_RAW_PCB 2
#define CONF_LWIP_STATS 1
#define CONF_LWIP_TCP_PCB 15
#define CONF_LWIP_TCP_PCB_LISTEN 10
#define CONF_LWIP_UDP_PCB 15


/*
 * mem_0 configuration
 *
 */

#define ALT_MODULE_CLASS_mem_0 altera_avalon_onchip_memory2
#define MEM_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define MEM_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define MEM_0_BASE 0x5020000
#define MEM_0_CONTENTS_INFO ""
#define MEM_0_DUAL_PORT 0
#define MEM_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define MEM_0_INIT_CONTENTS_FILE "Nios_mem_0"
#define MEM_0_INIT_MEM_CONTENT 1
#define MEM_0_INSTANCE_ID "NONE"
#define MEM_0_IRQ -1
#define MEM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define MEM_0_NAME "/dev/mem_0"
#define MEM_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define MEM_0_RAM_BLOCK_TYPE "AUTO"
#define MEM_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define MEM_0_SINGLE_CLOCK_OP 0
#define MEM_0_SIZE_MULTIPLE 1
#define MEM_0_SIZE_VALUE 131072
#define MEM_0_SPAN 131072
#define MEM_0_TYPE "altera_avalon_onchip_memory2"
#define MEM_0_WRITABLE 1


/*
 * mem_0 configuration as viewed by sgdma_tse_rx_0_m_write
 *
 */

#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_BASE 0x5020000
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_CONTENTS_INFO ""
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_DUAL_PORT 0
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_INIT_CONTENTS_FILE "Nios_mem_0"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_INIT_MEM_CONTENT 1
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_INSTANCE_ID "NONE"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_IRQ -1
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_NAME "/dev/mem_0"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_SINGLE_CLOCK_OP 0
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_SIZE_MULTIPLE 1
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_SIZE_VALUE 131072
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_SPAN 131072
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TSE_RX_0_M_WRITE_MEM_0_WRITABLE 1


/*
 * mem_0 configuration as viewed by sgdma_tse_tx_0_m_read
 *
 */

#define SGDMA_TSE_TX_0_M_READ_MEM_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define SGDMA_TSE_TX_0_M_READ_MEM_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define SGDMA_TSE_TX_0_M_READ_MEM_0_BASE 0x5020000
#define SGDMA_TSE_TX_0_M_READ_MEM_0_CONTENTS_INFO ""
#define SGDMA_TSE_TX_0_M_READ_MEM_0_DUAL_PORT 0
#define SGDMA_TSE_TX_0_M_READ_MEM_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_INIT_CONTENTS_FILE "Nios_mem_0"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_INIT_MEM_CONTENT 1
#define SGDMA_TSE_TX_0_M_READ_MEM_0_INSTANCE_ID "NONE"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_IRQ -1
#define SGDMA_TSE_TX_0_M_READ_MEM_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TSE_TX_0_M_READ_MEM_0_NAME "/dev/mem_0"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define SGDMA_TSE_TX_0_M_READ_MEM_0_RAM_BLOCK_TYPE "AUTO"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_SINGLE_CLOCK_OP 0
#define SGDMA_TSE_TX_0_M_READ_MEM_0_SIZE_MULTIPLE 1
#define SGDMA_TSE_TX_0_M_READ_MEM_0_SIZE_VALUE 131072
#define SGDMA_TSE_TX_0_M_READ_MEM_0_SPAN 131072
#define SGDMA_TSE_TX_0_M_READ_MEM_0_TYPE "altera_avalon_onchip_memory2"
#define SGDMA_TSE_TX_0_M_READ_MEM_0_WRITABLE 1


/*
 * sdram_controller_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sdram_controller_0 altera_avalon_new_sdram_controller
#define SDRAM_CONTROLLER_0_BASE 0x2000000
#define SDRAM_CONTROLLER_0_CAS_LATENCY 2
#define SDRAM_CONTROLLER_0_CONTENTS_INFO
#define SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 8
#define SDRAM_CONTROLLER_0_IRQ -1
#define SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define SDRAM_CONTROLLER_0_NAME "/dev/sdram_controller_0"
#define SDRAM_CONTROLLER_0_POWERUP_DELAY 200.0
#define SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x18
#define SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 9
#define SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define SDRAM_CONTROLLER_0_SHARED_DATA 0
#define SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define SDRAM_CONTROLLER_0_SPAN 33554432
#define SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define SDRAM_CONTROLLER_0_T_AC 8.0
#define SDRAM_CONTROLLER_0_T_MRD 3
#define SDRAM_CONTROLLER_0_T_RCD 30.0
#define SDRAM_CONTROLLER_0_T_RFC 90.0
#define SDRAM_CONTROLLER_0_T_RP 30.0
#define SDRAM_CONTROLLER_0_T_WR 30.0


/*
 * sdram_controller_0 configuration as viewed by sgdma_tse_rx_0_m_write
 *
 */

#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_BASE 0x2000000
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_CAS_LATENCY 2
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 8
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_IRQ -1
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_NAME "/dev/sdram_controller_0"
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_POWERUP_DELAY 200.0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x18
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 9
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_SPAN 33554432
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_T_AC 8.0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_T_MRD 3
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_T_RCD 30.0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_T_RFC 90.0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_T_RP 30.0
#define SGDMA_TSE_RX_0_M_WRITE_SDRAM_CONTROLLER_0_T_WR 30.0


/*
 * sdram_controller_0 configuration as viewed by sgdma_tse_tx_0_m_read
 *
 */

#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_BASE 0x2000000
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_CAS_LATENCY 2
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_CONTENTS_INFO
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_INIT_NOP_DELAY 0.0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_INIT_REFRESH_COMMANDS 8
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_IRQ -1
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_IS_INITIALIZED 1
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_NAME "/dev/sdram_controller_0"
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_POWERUP_DELAY 200.0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_REFRESH_PERIOD 7.8125
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_REGISTER_DATA_IN 1
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_ADDR_WIDTH 0x18
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_BANK_WIDTH 2
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_COL_WIDTH 9
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_DATA_WIDTH 16
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_NUM_BANKS 4
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_NUM_CHIPSELECTS 1
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SDRAM_ROW_WIDTH 13
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SHARED_DATA 0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SIM_MODEL_BASE 0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_SPAN 33554432
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_STARVATION_INDICATOR 0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_TRISTATE_BRIDGE_SLAVE ""
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_TYPE "altera_avalon_new_sdram_controller"
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_T_AC 8.0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_T_MRD 3
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_T_RCD 30.0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_T_RFC 90.0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_T_RP 30.0
#define SGDMA_TSE_TX_0_M_READ_SDRAM_CONTROLLER_0_T_WR 30.0


/*
 * sgdma_tse_rx_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tse_rx_0 altera_avalon_sgdma
#define SGDMA_TSE_RX_0_ADDRESS_WIDTH 32
#define SGDMA_TSE_RX_0_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TSE_RX_0_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TSE_RX_0_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TSE_RX_0_BASE 0x4002400
#define SGDMA_TSE_RX_0_BURST_DATA_WIDTH 8
#define SGDMA_TSE_RX_0_BURST_TRANSFER 0
#define SGDMA_TSE_RX_0_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TSE_RX_0_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TSE_RX_0_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TSE_RX_0_CONTROL_DATA_WIDTH 8
#define SGDMA_TSE_RX_0_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TSE_RX_0_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TSE_RX_0_DESCRIPTOR_READ_BURST 0
#define SGDMA_TSE_RX_0_DESC_DATA_WIDTH 32
#define SGDMA_TSE_RX_0_HAS_READ_BLOCK 0
#define SGDMA_TSE_RX_0_HAS_WRITE_BLOCK 1
#define SGDMA_TSE_RX_0_IN_ERROR_WIDTH 6
#define SGDMA_TSE_RX_0_IRQ 0
#define SGDMA_TSE_RX_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TSE_RX_0_NAME "/dev/sgdma_tse_rx_0"
#define SGDMA_TSE_RX_0_OUT_ERROR_WIDTH 0
#define SGDMA_TSE_RX_0_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TSE_RX_0_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TSE_RX_0_SPAN 64
#define SGDMA_TSE_RX_0_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TSE_RX_0_STREAM_DATA_WIDTH 32
#define SGDMA_TSE_RX_0_SYMBOLS_PER_BEAT 4
#define SGDMA_TSE_RX_0_TYPE "altera_avalon_sgdma"
#define SGDMA_TSE_RX_0_UNALIGNED_TRANSFER 0
#define SGDMA_TSE_RX_0_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TSE_RX_0_WRITE_BURSTCOUNT_WIDTH 4


/*
 * sgdma_tse_tx_0 configuration
 *
 */

#define ALT_MODULE_CLASS_sgdma_tse_tx_0 altera_avalon_sgdma
#define SGDMA_TSE_TX_0_ADDRESS_WIDTH 32
#define SGDMA_TSE_TX_0_ALWAYS_DO_MAX_BURST 1
#define SGDMA_TSE_TX_0_ATLANTIC_CHANNEL_DATA_WIDTH 4
#define SGDMA_TSE_TX_0_AVALON_MM_BYTE_REORDER_MODE 0
#define SGDMA_TSE_TX_0_BASE 0x4002440
#define SGDMA_TSE_TX_0_BURST_DATA_WIDTH 8
#define SGDMA_TSE_TX_0_BURST_TRANSFER 0
#define SGDMA_TSE_TX_0_BYTES_TO_TRANSFER_DATA_WIDTH 16
#define SGDMA_TSE_TX_0_CHAIN_WRITEBACK_DATA_WIDTH 32
#define SGDMA_TSE_TX_0_COMMAND_FIFO_DATA_WIDTH 104
#define SGDMA_TSE_TX_0_CONTROL_DATA_WIDTH 8
#define SGDMA_TSE_TX_0_CONTROL_SLAVE_ADDRESS_WIDTH 0x4
#define SGDMA_TSE_TX_0_CONTROL_SLAVE_DATA_WIDTH 32
#define SGDMA_TSE_TX_0_DESCRIPTOR_READ_BURST 0
#define SGDMA_TSE_TX_0_DESC_DATA_WIDTH 32
#define SGDMA_TSE_TX_0_HAS_READ_BLOCK 1
#define SGDMA_TSE_TX_0_HAS_WRITE_BLOCK 0
#define SGDMA_TSE_TX_0_IN_ERROR_WIDTH 0
#define SGDMA_TSE_TX_0_IRQ 1
#define SGDMA_TSE_TX_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define SGDMA_TSE_TX_0_NAME "/dev/sgdma_tse_tx_0"
#define SGDMA_TSE_TX_0_OUT_ERROR_WIDTH 1
#define SGDMA_TSE_TX_0_READ_BLOCK_DATA_WIDTH 32
#define SGDMA_TSE_TX_0_READ_BURSTCOUNT_WIDTH 4
#define SGDMA_TSE_TX_0_SPAN 64
#define SGDMA_TSE_TX_0_STATUS_TOKEN_DATA_WIDTH 24
#define SGDMA_TSE_TX_0_STREAM_DATA_WIDTH 32
#define SGDMA_TSE_TX_0_SYMBOLS_PER_BEAT 4
#define SGDMA_TSE_TX_0_TYPE "altera_avalon_sgdma"
#define SGDMA_TSE_TX_0_UNALIGNED_TRANSFER 1
#define SGDMA_TSE_TX_0_WRITE_BLOCK_DATA_WIDTH 32
#define SGDMA_TSE_TX_0_WRITE_BURSTCOUNT_WIDTH 4


/*
 * timer_0 configuration
 *
 */

#define ALT_MODULE_CLASS_timer_0 altera_avalon_timer
#define TIMER_0_ALWAYS_RUN 0
#define TIMER_0_BASE 0x5041020
#define TIMER_0_COUNTER_SIZE 32
#define TIMER_0_FIXED_PERIOD 0
#define TIMER_0_FREQ 100000000
#define TIMER_0_IRQ 3
#define TIMER_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define TIMER_0_LOAD_VALUE 99999
#define TIMER_0_MULT 0.001
#define TIMER_0_NAME "/dev/timer_0"
#define TIMER_0_PERIOD 1
#define TIMER_0_PERIOD_UNITS "ms"
#define TIMER_0_RESET_OUTPUT 0
#define TIMER_0_SNAPSHOT 1
#define TIMER_0_SPAN 32
#define TIMER_0_TICKS_PER_SEC 1000
#define TIMER_0_TIMEOUT_PULSE_OUTPUT 0
#define TIMER_0_TYPE "altera_avalon_timer"


/*
 * tse_descriptor_memory_0 configuration
 *
 */

#define ALT_MODULE_CLASS_tse_descriptor_memory_0 altera_avalon_onchip_memory2
#define TSE_DESCRIPTOR_MEMORY_0_ALLOW_IN_SYSTEM_MEMORY_CONTENT_EDITOR 0
#define TSE_DESCRIPTOR_MEMORY_0_ALLOW_MRAM_SIM_CONTENTS_ONLY_FILE 0
#define TSE_DESCRIPTOR_MEMORY_0_BASE 0x4000000
#define TSE_DESCRIPTOR_MEMORY_0_CONTENTS_INFO ""
#define TSE_DESCRIPTOR_MEMORY_0_DUAL_PORT 1
#define TSE_DESCRIPTOR_MEMORY_0_GUI_RAM_BLOCK_TYPE "AUTO"
#define TSE_DESCRIPTOR_MEMORY_0_INIT_CONTENTS_FILE "Nios_tse_descriptor_memory_0"
#define TSE_DESCRIPTOR_MEMORY_0_INIT_MEM_CONTENT 1
#define TSE_DESCRIPTOR_MEMORY_0_INSTANCE_ID "NONE"
#define TSE_DESCRIPTOR_MEMORY_0_IRQ -1
#define TSE_DESCRIPTOR_MEMORY_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE_DESCRIPTOR_MEMORY_0_NAME "/dev/tse_descriptor_memory_0"
#define TSE_DESCRIPTOR_MEMORY_0_NON_DEFAULT_INIT_FILE_ENABLED 0
#define TSE_DESCRIPTOR_MEMORY_0_RAM_BLOCK_TYPE "AUTO"
#define TSE_DESCRIPTOR_MEMORY_0_READ_DURING_WRITE_MODE "DONT_CARE"
#define TSE_DESCRIPTOR_MEMORY_0_SINGLE_CLOCK_OP 0
#define TSE_DESCRIPTOR_MEMORY_0_SIZE_MULTIPLE 1
#define TSE_DESCRIPTOR_MEMORY_0_SIZE_VALUE 8192
#define TSE_DESCRIPTOR_MEMORY_0_SPAN 8192
#define TSE_DESCRIPTOR_MEMORY_0_TYPE "altera_avalon_onchip_memory2"
#define TSE_DESCRIPTOR_MEMORY_0_WRITABLE 1


/*
 * tse_mac_0 configuration
 *
 */

#define ALT_MODULE_CLASS_tse_mac_0 altera_eth_tse
#define TSE_MAC_0_BASE 0x4002000
#define TSE_MAC_0_ENABLE_MACLITE 1
#define TSE_MAC_0_FIFO_WIDTH 32
#define TSE_MAC_0_IRQ -1
#define TSE_MAC_0_IRQ_INTERRUPT_CONTROLLER_ID -1
#define TSE_MAC_0_IS_MULTICHANNEL_MAC 0
#define TSE_MAC_0_MACLITE_GIGE 0
#define TSE_MAC_0_MDIO_SHARED 0
#define TSE_MAC_0_NAME "/dev/tse_mac_0"
#define TSE_MAC_0_NUMBER_OF_CHANNEL 1
#define TSE_MAC_0_NUMBER_OF_MAC_MDIO_SHARED 1
#define TSE_MAC_0_PCS 0
#define TSE_MAC_0_PCS_ID 0
#define TSE_MAC_0_PCS_SGMII 0
#define TSE_MAC_0_RECEIVE_FIFO_DEPTH 4096
#define TSE_MAC_0_REGISTER_SHARED 0
#define TSE_MAC_0_RGMII 0
#define TSE_MAC_0_SPAN 1024
#define TSE_MAC_0_TRANSMIT_FIFO_DEPTH 4096
#define TSE_MAC_0_TYPE "altera_eth_tse"
#define TSE_MAC_0_USE_MDIO 1


/*
 * uart_0 configuration
 *
 */

#define ALT_MODULE_CLASS_uart_0 altera_avalon_uart
#define UART_0_BASE 0x5041000
#define UART_0_BAUD 115200
#define UART_0_DATA_BITS 8
#define UART_0_FIXED_BAUD 1
#define UART_0_FREQ 100000000
#define UART_0_IRQ 4
#define UART_0_IRQ_INTERRUPT_CONTROLLER_ID 0
#define UART_0_NAME "/dev/uart_0"
#define UART_0_PARITY 'N'
#define UART_0_SIM_CHAR_STREAM ""
#define UART_0_SIM_TRUE_BAUD 0
#define UART_0_SPAN 32
#define UART_0_STOP_BITS 1
#define UART_0_SYNC_REG_DEPTH 2
#define UART_0_TYPE "altera_avalon_uart"
#define UART_0_USE_CTS_RTS 0
#define UART_0_USE_EOP_REGISTER 0

#endif /* __SYSTEM_H_ */
